/**
 * APPS Dataset Importer for ThinkDSA
 *
 * Reads apps_problems.json (generated by download_apps.py) and upserts
 * all problems into the ThinkDSA database via Prisma.
 *
 * Usage (run from ThinkDSA/apps/api):
 *   npx ts-node ../../scripts/import_apps.ts
 *   npx ts-node ../../scripts/import_apps.ts --file ../../scripts/apps_problems.json
 *   npx ts-node ../../scripts/import_apps.ts --limit 100
 */

import { PrismaClient } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';

const prisma = new PrismaClient();

interface AppsProblem {
    title: string;
    slug: string;
    statement: string;
    difficulty: string;
    topic: string;
    metadata: string;
    testCases: string;
}

function parseArgs() {
    const args = process.argv.slice(2);
    const options: { file: string; limit: number; batchSize: number } = {
        file: path.resolve(__dirname, 'apps_problems.json'),
        limit: Infinity,
        batchSize: 50,
    };
    for (let i = 0; i < args.length; i++) {
        if (args[i] === '--file' && args[i + 1]) options.file = path.resolve(args[++i]);
        if (args[i] === '--limit' && args[i + 1]) options.limit = parseInt(args[++i], 10);
        if (args[i] === '--batchSize' && args[i + 1]) options.batchSize = parseInt(args[++i], 10);
    }
    return options;
}

async function main() {
    const opts = parseArgs();

    console.log('📂 ThinkDSA — APPS Dataset Importer');
    console.log(`   File: ${opts.file}`);

    if (!fs.existsSync(opts.file)) {
        console.error(`\n❌ File not found: ${opts.file}`);
        console.error('   Run the Python downloader first:');
        console.error('   python scripts/download_apps.py --count 200');
        process.exit(1);
    }

    const raw = fs.readFileSync(opts.file, 'utf-8');
    let problems: AppsProblem[] = JSON.parse(raw);

    if (opts.limit !== Infinity) {
        problems = problems.slice(0, opts.limit);
    }

    console.log(`   Problems to import: ${problems.length}`);

    const batchSize = opts.batchSize;
    let inserted = 0;
    let skipped = 0;
    let failed = 0;

    for (let i = 0; i < problems.length; i += batchSize) {
        const batch = problems.slice(i, i + batchSize);
        await Promise.all(
            batch.map(async (p) => {
                try {
                    await prisma.problem.upsert({
                        where: { slug: p.slug },
                        update: {
                            title: p.title,
                            statement: p.statement,
                            difficulty: p.difficulty,
                            topic: p.topic,
                            metadata: p.metadata,
                            testCases: p.testCases,
                        },
                        create: {
                            title: p.title,
                            slug: p.slug,
                            statement: p.statement,
                            difficulty: p.difficulty,
                            topic: p.topic,
                            metadata: p.metadata,
                            testCases: p.testCases,
                        },
                    });
                    inserted++;
                } catch (e: any) {
                    if (e?.code === 'P2002') {
                        skipped++; // unique constraint: already exists
                    } else {
                        failed++;
                        console.error(`   ⚠️  Failed to insert "${p.slug}": ${e?.message}`);
                    }
                }
            })
        );

        const done = Math.min(i + batchSize, problems.length);
        process.stdout.write(`\r   Progress: ${done}/${problems.length} (✅ ${inserted}  ⏭️  ${skipped}  ❌ ${failed})`);
    }

    console.log('\n');

    // Summary
    const totalInDb = await prisma.problem.count();
    const byDiff = await prisma.problem.groupBy({ by: ['difficulty'], _count: true });

    console.log('✅ Import complete!');
    console.log(`   Inserted/updated : ${inserted}`);
    console.log(`   Skipped (existed): ${skipped}`);
    console.log(`   Failed           : ${failed}`);
    console.log(`\n   Total problems in DB: ${totalInDb}`);
    byDiff.forEach(({ difficulty, _count }: { difficulty: string; _count: number }) => {
        console.log(`     ${difficulty}: ${_count}`);
    });
}

main()
    .catch((e) => {
        console.error('\n❌ Importer crashed:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
